### ISSUE TITLE
[FEATURE] UI Assets Overhaul

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#127]
###### **Feature description**
We provide a lot of UI assets w/ space warp, but the GUISkin is incomplete in the assets we provide

- [ ] UI Scrollbar - Not yet added
- [ ] UI Click Through Blocker - Started in #49
- [ ] UI Boarders - Requested in #66 
- [x] UI Scaling Window - Added in #166 
- [ ] UI Scaling Elements - The window itself now scales with resolution, now we gotta make the elements scale too

###### **Solution proposal**
Complete the assets for the Space Warp GUISkin

**Comment by EwyBoy** [comment]
Reassigned you here @Rexicon226 as I closed #66 and made it a sub task of this issue.
